version: '3.4'

services:  
  api:
    build:
      context: ./
      dockerfile: Dockerfile
      network: host
    container_name: 'api'
    restart: always
    ports:
      - "8080:8080"
    expose:
      - "8080"
    networks:
      - app-network
    depends_on:
      - mongodb
    env_file:
      - ./.env.docker

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    expose:
      - "27017"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
